### ISSUE TITLE
Hey Jimmy, this is a dumb question, but how do I build?

### ISSUE THREAD

**Issue by zivshek** [JimmyLord/MyEngine#1]
constantly hitting "Configuring incomplete, errors occurred!" with CMake.

**Comment by JimmyLord** [comment]
The CMake files are broken, I used them for a linux build over a year ago and haven't updated them since.

Start with the "ProjectEngineEmpty" project and open "GameEmptyReplaceMe/EmptyReplaceMe.sln" in VS2017.  I use VS2010, but it should offer to update and work from there.

**Comment by zivshek** [comment]
thx for the quick reply. There is still an error in pthread.h(321): error C2011: 'timespec': 'struct' type redefinition

**Comment by JimmyLord** [comment]
I'll test and fix later, but put these lines:

#if WINVER >= 0x0602
#define _TIMESPEC_DEFINED
#endif

before this include, around line 338 of MyFrameworkPCH.h:

#include "../../Libraries/pthreads-w32/include/pthread.h"

if this causes issues with _TIMESPEC_DEFINED being defined more than once, remove the old define from MyFramework.h (line 140ish)

**Comment by JimmyLord** [comment]
Sorry for the trouble but I just pushed some fixes to make the code compile in VS2017.

If you update the "ProjectEngineEmpty" project and its submodules, it should work.

I only tested the "EditorDebug" configuration.

Don't forget to run "Windows-CreateSymLinksForData.bat" which is in the root folder, otherwise you'll get a crash at startup about a missing font file.
